In [43]:
import os
from PIL import Image
import numpy as np
from sklearn.preprocessing import StandardScaler
import pandas as pd
from sklearn.preprocessing import StandardScaler
import cv2

from tensorflow.keras.preprocessing.image import img_to_array
from tensorflow.keras.models import load_model
from keras.applications.mobilenet_v3 import preprocess_input as preprocess_input_mobilenet



In [4]:
if str(os.getcwdb()[-3:]).split("'")[1] != 'src':
    for _ in range(2):
        os.chdir(os.path.dirname(os.getcwdb()))


In [45]:
model_cnn = load_model(r'src\models\predict_from_images\price_prediction_images.h5')

model_cnn


In [52]:
image_path = '.streamlit/images/sample_image.jpg'

img = Image.open(image_path)
img = preprocess_input_mobilenet(img)
img = img.resize((224, 224))
img_array = img_to_array(img)


In [53]:
img_array.shape

(224, 224, 3)

In [54]:
img_array = np.expand_dims(img_array, axis=0)

In [55]:
img_array.shape

(1, 224, 224, 3)

In [22]:
prediction = model_cnn.predict(img_array)

prediction.shape


1/1 [==============================] - 5s 5s/step


(1, 1)

In [23]:
prediction[0].shape

(1,)

In [24]:
prediction[0]


array([-0.09114669], dtype=float32)

In [26]:
import numpy as np
import joblib
import time
from sklearn.neighbors import KNeighborsRegressor


# The dataframes are obtained using pickle
# If the image generator were to be used directly, the result would oscillate slightly
X_train, X_test, y_train, y_test = joblib.load(r'src\fixed_images_dataframe.pkl')

X = np.concatenate([X_train, X_test])
y = np.concatenate([y_train, y_test[:, 0]])
print(X_train)

# Training
print('--- Training started ---')

start_time = time.time()

model = KNeighborsRegressor(n_neighbors=6, 
                            weights='distance',
                            p=1,
                            algorithm='brute', 
                            metric='chebyshev', 
                            leaf_size=1
                            )

model.fit(X, y)

execution_time = time.time() - start_time

print(f'--- Training done in {round(execution_time, 2)} sec/s ---\n')


     predicted_price  weight (carat)
463         0.169126            0.81
0          -0.212551            0.31
608        -0.152704            0.40
606        -0.074916            0.90
523        -0.128174            0.30
..               ...             ...
277        -0.133864            0.42
817        -0.218367            0.50
255        -0.141653            0.50
320        -0.283554            0.31
836        -0.114105            0.50

[636 rows x 2 columns]
--- Training started ---
--- Training done in 0.0 sec/s ---



In [27]:
print(len(X_train))

X_train

636


predicted_price  weight (carat)
463         0.169126            0.81
0          -0.212551            0.31
608        -0.152704            0.40
606        -0.074916            0.90
523        -0.128174            0.30
..               ...             ...
277        -0.133864            0.42
817        -0.218367            0.50
255        -0.141653            0.50
320        -0.283554            0.31
836        -0.114105            0.50

[636 rows x 2 columns]

In [28]:
print(len(X_test))

X_test

273


predicted_price  weight (carat)
276        -0.117133            0.50
91         -0.103409            0.33
596        -0.136340            0.50
542        -0.323543            0.51
221         0.012185            2.01
..               ...             ...
348        -0.249030            0.42
236        -0.385796            0.51
386        -0.137911            0.52
442        -0.187529            0.32
541         0.099738            0.50

[273 rows x 2 columns]

In [25]:
print(len(y_train))

y_train

636


463    0.025735
0     -0.343747
608   -0.372618
606   -0.054211
523   -0.348686
         ...   
277   -0.230806
817   -0.151414
255   -0.073064
320   -0.350294
836   -0.174496
Name: original_price, Length: 636, dtype: float64

In [26]:
print(len(y_test))

y_test

273


array([[ 2028.32],
       [ 1056.32],
       [ 2030.78],
       [ 1263.85],
       [30806.38],
       [ 2231.4 ],
       [ 1326.33],
       [ 2040.22],
       [  933.68],
       [ 1032.64],
       [ 2485.75],
       [ 2063.52],
       [ 1538.75],
       [ 1118.85],
       [  896.75],
       [ 1145.9 ],
       [  975.06],
       [ 2106.2 ],
       [ 2096.53],
       [ 1310.83],
       [ 1867.55],
       [  963.92],
       [ 1168.91],
       [ 1695.66],
       [ 2040.5 ],
       [13500.16],
       [ 2079.3 ],
       [ 2070.42],
       [ 1983.44],
       [  979.42],
       [  875.07],
       [ 1251.53],
       [ 3632.78],
       [ 3229.56],
       [ 1340.19],
       [ 4788.35],
       [ 1311.2 ],
       [ 1100.26],
       [ 1329.02],
       [ 1698.05],
       [ 2028.2 ],
       [ 2089.31],
       [ 1986.07],
       [ 2070.33],
       [ 1865.76],
       [  904.35],
       [ 4453.83],
       [ 2040.02],
       [ 3173.58],
       [ 1986.7 ],
       [ 1587.81],
       [ 1036.38],
       [ 118

In [27]:
print(len(X))

X


909


array([[ 0.16912559,  0.81      ],
       [-0.21255109,  0.31      ],
       [-0.15270379,  0.4       ],
       ...,
       [-0.13791114,  0.52      ],
       [-0.18752857,  0.32      ],
       [ 0.09973814,  0.5       ]])

In [28]:
print(len(y))

y


909


array([ 2.57350243e-02, -3.43746765e-01, -3.72618492e-01, -5.42107235e-02,
       -3.48685908e-01, -8.04618428e-02, -2.12965474e-01, -1.05729903e-01,
        3.09277321e-01, -6.18420169e-02, -5.82065535e-02,  1.48181989e-03,
       -3.22842850e-01, -2.71861571e-01, -9.39093477e-02, -7.92456054e-02,
       -2.68533479e-01, -3.26393522e-01,  3.81668618e-01, -3.21592166e-01,
       -3.16727217e-01, -9.94446852e-02, -1.79843541e-01,  3.46204302e-01,
       -3.40725881e-02,  3.43207429e-01, -2.72770437e-01, -2.98017299e-01,
       -6.34080219e-02,  3.57563964e-02, -2.42345954e-01, -6.89910549e-02,
       -8.55944176e-02, -3.73802932e-01, -8.17681719e-02, -3.85374411e-01,
       -3.60813835e-01, -3.49944541e-01, -2.70491648e-01, -2.33238747e-01,
       -2.64770827e-01,  3.03826939e-02, -2.49203355e-02, -2.37738030e-01,
       -2.10456156e-01, -4.09140060e-01, -4.28035297e-02,  2.04514135e-02,
       -1.64416669e-01, -9.26507142e-02, -3.73996364e-01, -7.16805559e-02,
       -2.85870824e-01,  

In [29]:
df_to_predict = pd.DataFrame(data={'estimated_price': prediction[0], 'weight': 0.53})


In [30]:
df_to_predict

estimated_price  weight
0        -0.091147    0.53

In [31]:
prediction[0][0]

-0.091146685

In [32]:
np.array([prediction[0][0], 0.53])

array([-0.09114669,  0.53      ])

In [33]:
model.predict(np.array([prediction[0][0], 0.53]).reshape(1, -1))


array([434.28083272])